
language: python

python:
  - "2.6"
  - "2.7"

install:
  - "pip install -r requirements.txt"

script:
  - "nosetests"

env:
  - MOCKERNAUT_SETTINGS=${TRAVIS_BUILD_DIR}/config/test_config.py

before_script:
  - "mysql test < sql/schema.sql"
