
language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

install:
  - "pip install -r requirements.txt"
  - if [[ "$(python -c 'import sys; print sys.version_info[:2]')" == "(2, 6)" ]]; then pip install unittest2; fi

script:
  - "nosetests -v"

env:
  - MOCKERNAUT_SETTINGS=${TRAVIS_BUILD_DIR}/config/test_config.py

before_script:
  - "mysql -e 'CREATE DATABASE mockernaut_test'"
  - "mysql mockernaut_test < sql/schema.sql"
