
language: python

python:
  - "2.6"
  - "2.7"

install:
  - "pip install -r requirements.txt"

script:
  - "nosetests -v"

env:
  - MOCKERNAUT_SETTINGS=${TRAVIS_BUILD_DIR}/config/test_config.py

before_script:
  - "mysql -e 'create database mockernaut_test;'"
  - "mysql mockernaut_test < ${TRAVIS_BUILD_DIR}/sql/schema.sql"
