
language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - "python setup.py install"
  - if [[ "$(python -c 'import sys; print sys.version_info[:2]')" == "(2, 6)" ]]; then pip install unittest2; fi
  - if [[ "$(python -c 'import sys; print sys.version_info[:2]')" == "(2, 7)" ]]; then pip install mock; fi
  - "make inittestdb"
  - "make initdev"

script:
  - "make test"

env:
  - MOCKERNAUT_SETTINGS=${TRAVIS_BUILD_DIR}/config/test_config.py

before_script:
  - "make check"
